#!/bin/sh

# TODO: make scripts parsing /etc/config/firewall
echo " * starting firewall ...          [ TBD ]"
exit 0

echo -n " * starting firewall ...         "
if true > /dev/null 2> /dev/null; then
	echo "[ OK ]"
else
	echo "[ FAILED ]"
	exit 1
fi

exit 0
