#!/bin/sh

/etc/init.d/S01mountvirtfs
/etc/init.d/S02hostname
/etc/init.d/S08loopback
/etc/init.d/S09syslog
/etc/init.d/S09klog
/etc/init.d/S10mdev
/etc/init.d/S10modules-init
/etc/init.d/S35mountall

if /etc/init.d/S10networking; then
	echo " * network ...                   [ OK ]"
	/etc/init.d/S11iptables
#	/etc/init.d/S15dnsmasq
#	/etc/init.d/S23ntp
	/etc/init.d/S20ssh
#	/etc/init.d/S20telnet
	/etc/init.d/S20inetd
#	/etc/init.d/S20samba
#	/etc/init.d/S91httpd
else
	echo " * Network ...                   [ FAILED ]"
fi

/etc/init.d/S99gpio

echo
echo "Network Gateway ready"
echo

exit 0
